name: clang-format Check
on:
  pull_request:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        extensions: 'c,h,cpp,hpp'
        clangFormatVersion: 13
        style: file

